# Generated by Django 4.2.11 on 2024-05-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HasilPrediksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('lokasi', models.CharField(max_length=50)),
                ('persentase_model_Random_Forest', models.CharField(max_length=50)),
                ('persentase_model_SVM', models.CharField(max_length=50)),
            ],
        ),
    ]
